### ISSUE TITLE
yaml is underwhelming

### ISSUE THREAD

**Issue by ghostsquad** [juliusmh/snippit#3]
```shell
snippit --syntax yaml --out snippet.png --decorations --theme monokai-dark < workflow.yaml
```

![snippet](https://user-images.githubusercontent.com/903488/167760303-03eb86db-6efd-41d0-a04b-8144cfcaa4c9.png)

compared to syntax highlighting in vscode:

![image](https://user-images.githubusercontent.com/903488/167760394-42df69ae-2161-409e-8f59-fdf20f1f6b4e.png)

**Comment by juliusmh** [comment]
True. The highlighting is based on this file:
https://github.com/zyedidia/highlight/blob/master/syntax_files/yaml.yaml

I currently don't have the time to fix it though. Feel free to file a PR that adds proper highlighting!

**Comment by juliusmh** [comment]
Working on a new version 😉 

<img width="687" alt="image" src="https://github.com/juliusmh/snippit/assets/7480158/454ee921-0c68-4f68-85ff-29c09e44bfe8">


<img width="508" alt="image" src="https://github.com/juliusmh/snippit/assets/7480158/c94362df-57af-4264-b0db-404d8e84657d">

**Comment by ghostsquad** [comment]
Thanks!
